name: New Release

on:
  push:
    branches:
      - master

jobs:
  call-deploy-frontend:
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      frontend_name: 'gi-frontend'
      repo_full_name: ${{ github.repository }}
      ref: ${{ github.ref }}
      deployment_name: "beta"
      pr_repo: ${{ vars.PR_REPO }}
      show_dev_components: true
    secrets: inherit
