name: New Beta GO Release

on:
  push:
    branches:
      - master

# Only allow the most recent run of beta release to complete, if multiple are queued.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  call-build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    with:
      frontend_name: 'frontend'
      deployment_name: 'beta'
      repo_var_name: 'PR_REPO'
      repo_deploy_secret_name: 'PR_REPO_SSH_KEY'
      show_dev_components: true
