name: Build GO-next PR
run-name: Build GO-next for ${{ github.event.number }} - ${{ github.event.pull_request.title }}

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - 'apps/frontend/**'
      - 'apps/frontend-e2e/**'
      - 'apps/somnia/**'
      - 'apps/somnia-e2e/**'
      - 'apps/sr-frontend/**'
      - 'apps/sr-frontend-e2e/**'
      - 'apps/zzz-frontend/**'
      - 'apps/zzz-frontend-e2e/**'
      - 'libs/gi/i18n-node/**'
      - 'libs/sr/**'
      - 'libs/zzz/**'
    types: [opened, reopened, synchronize, labeled]

jobs:
  call-build:
    uses: ./.github/workflows/build-frontend.yml
    with:
      frontend_name: 'gi-frontend'
      deployment_name: ${{ github.event.number }}
      repo_name: ${{ vars.PR_REPO }}
      repo_deploy_secret_name: 'PR_REPO_SSH_KEY'
      show_dev_components: ${{ contains(github.event.pull_request.labels.*.name, 'showDevComponents') }}
