name: Build ZO Release

on:
  pull_request:
    types: [closed]

jobs:
  call-build-frontend:
    uses: ./.github/workflows/build-frontend.yml
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'zo-release') }}
    with:
      frontend_name: 'zzz-frontend'
      deployment_name: ''
      repo_var_name: 'ZO_REPO'
      repo_deploy_secret_name: 'ZO_REPO_SSH_KEY'
      show_dev_components: false
      nested_deployments: false
  create-release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: ${{ github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'zo-release') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Get version
        id: get-version
        run: |
          echo "version=$(printf '%s' '${{ github.event.pull_request.title }}' | awk '{print $4}')" >> $GITHUB_OUTPUT
      - name: Make release
        if: steps.get-version.outputs.version != ''
        run: |
          TEMP_FILE=$(mktemp)
          # List tags for ZO and get the latest one
          git tag --list
          oldTag=$(git tag --list '*+zo' --sort=creatordate | tail -n 1)
          echo "**What's Changed**\n" >> $TEMP_FILE
          git log --pretty='format:* %s' $oldTag..HEAD -- . ':!libs/gi' ':!libs/sr' :!apps/frontend' :!apps/frontend-e2e' :!apps/gi-frontend' :!apps/gi-frontend-e2e' :!apps/sr-frontend' :!apps/sr-frontend-e2e' :!apps/somnia' :!apps/somnia-e2e' >> $TEMP_FILE
          echo "\n\n**Full Changelog**: https://github.com/${{ github.repository }}/compare/$oldTag..${{ steps.get-version.outputs.version }}" >> $TEMP_FILE
          gh release create ${{ steps.get-version.outputs.version }} -F $TEMP_FILE -t ${{steps.get-version.outputs.version}} --target $(git rev-parse HEAD)
        env:
          GH_TOKEN: ${{ github.token }}
