name: Build ZO PR
run-name: Build ZO for ${{ github.event.number }} - ${{ github.event.pull_request.title }}

permissions:
  contents: read

on:
  pull_request:
    paths-ignore:
      - 'apps/frontend/**'
      - 'apps/frontend-e2e/**'
      - 'apps/gi-frontend/**'
      - 'apps/gi-frontend-e2e/**'
      - 'apps/sr-frontend/**'
      - 'apps/sr-frontend-e2e/**'
      - 'apps/somnia/**'
      - 'apps/somnia-e2e/**'
      - 'libs/gi/**'
      - 'libs/sr/**'
    types: [opened, reopened, synchronize, labeled]

jobs:
  call-build:
    uses: ./.github/workflows/build-frontend.yml
    with:
      frontend_name: 'zzz-frontend'
      deployment_name: ${{ github.event.number }}
      show_dev_components: ${{ contains(github.event.pull_request.labels.*.name, 'showDevComponents') }}
