name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Yarn Install
        run: |
          yarn install --immutable --immutable-cache
      - name: Run lint
        run: |
          yarn run nx run-many --target=eslint:lint --fix=false --max-warnings=0
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Get Cache Key
        id: get-cache-key
        run: |
          echo "key=$(git ls-tree -r HEAD | grep '^160000' | sha256sum | cut -d " " -f 1)" >> $GITHUB_OUTPUT
      - uses: actions/cache/restore@v4
        with:
          path: .git/modules
          key: submodule-${{ steps.get-cache-key.outputs.key }}
          restore-keys: |
            submodule-
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Yarn Install
        run: |
          yarn install --immutable --immutable-cache
      - name: Run Tests
        run: |
          yarn run nx run-many --target=test
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }} # Force checking of the whole repo when running on pushes to master
      - name: Fetch master
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          git fetch --no-tags --no-recurse-submodules --filter=blob:none origin +master:refs/heads/master
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Yarn Install
        run: |
          yarn install --immutable --immutable-cache
      - name: Check Formatting
        run: |
          yarn biome ci --changed
  typecheck:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Yarn Install
        run: |
          yarn install --immutable --immutable-cache
      - name: Check types
        run: |
          yarn run nx run-many --target=typecheck
  gen-file:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Get Cache Key
        id: get-cache-key
        run: |
          echo "key=$(git ls-tree -r HEAD | grep '^160000' | sha256sum | cut -d " " -f 1)" >> $GITHUB_OUTPUT
      - uses: actions/cache@v4
        with:
          path: .git/modules
          key: submodule-${{ steps.get-cache-key.outputs.key }}
          restore-keys: |
            submodule-
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Sparse Checkout
        run: |
          $(cd libs/gi/dm/GenshinData  && git sparse-checkout set TextMap ExcelBinOutput)
          $(cd libs/sr/dm/StarRailData && git sparse-checkout set TextMap ExcelOutput)
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Yarn Install
        run: |
          yarn install --immutable --immutable-cache
      - name: Check Gen File
        run: |
          yarn run nx run-many -t gen-file
          test -z "$(git status --porcelain | tee /dev/stderr)"
